import { ColorModeScript } from "@chakra-ui/react";
import { Providers } from "./providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ColorModeScript />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
